songpa:
  homepage: "https://www.splib.or.kr/intro/index.do"
  note: "송파구 통합도서관"
  search_box:
    - "#mainSearchKeyword"
    - "#topSearchKeyword"
    - "input[name='searchKeyword']"
  submit_btn:
    - "#mainSearchBtn"
    - "#topSearchBtn"
    - ".btnSearch"

gangnam:
  homepage: "https://library.gangnam.go.kr/intro/index.do"
  note: "강남구 통합도서관"

seocho:
  homepage: "https://public.seocholib.or.kr"
  note: "서초구립도서관"