# # 정적 인덱스(Static Index)
# # - 각 구별 공공도서관 포털 URL과 검색창/버튼 셀렉터를 저장
# # - 여기서는 강남구만 우선 등록
# # - 향후 서초, 송파, 관악 등 확장 가능

# # TODO search_box, submit_btn 삭제
# gangnam:
#   display_name: "강남구 통합도서관"
#   homepage: "https://library.gangnam.go.kr/intro/index.do"
#   search_box:
#     - "#mainSearchKeyword"
#     - "#searchKeyword"
#     - "#totalSearch"
#     - "input[name='keyword']"
#   submit_btn:
#     - "#mainSearchBtn"
#     - "#searchBtn"


# songpa:
#   homepage: "https://www.splib.or.kr/intro/index.do"
#   search_box: ["#searchKeyword", "#q", "input[name='searchKey']", "input[type='text']"]
#   submit_btn: ["#searchBtn", "button.searchBtn", ".btn_search"]


# seocho:
#   homepage: "https://public.seocholib.or.kr/"
#   search_box:
#     - "#searchKeyword"
#     - "#q"
#     - "input[name='searchKey']"
#     - "input[type='text']"
#     - "input[name='keyword']"
#   submit_btn:
#     - "#searchBtn"
#     - "button.searchBtn"
#     - ".btn_search"
#     - "button[type='submit']"

# 00_src/config/catalog_index.yaml

songpa:
  homepage: "https://www.splib.or.kr/intro/index.do"
  simple_search_path: "/intro/menu/10003/program/30001/plusSearchSimple.do"   # ← NEW
  search_box:
    - "#searchKeyword"
    - "#q"
    - "input[name='searchKey']"
    - "input[type='text']"
  submit_btn:
    - "#searchBtn"
    - "button.searchBtn"
    - ".btn_search"

gangnam:
  homepage: "https://library.gangnam.go.kr/intro/index.do"
  simple_search_path: "/intro/menu/12481/program/30009/plusSearchSimple.do"   # ← NEW (경로는 실제 페이지에서 F12로 확인 필요)
  search_box:
    - "#mainSearchKeyword"
    - "#searchKeyword"
    - "#totalSearch"
    - "input[name='keyword']"
  submit_btn:
    - "#mainSearchBtn"
    - "#searchBtn"