defaults:
  search_box:
    - "#searchKeyword"
    - "#q"
    - "input[name='keyword']"
    - "input[name='searchKey']"
    - "input[type='text']"
  submit_btn:
    - "#searchBtn"
    - "button.searchBtn"
    - ".btn_search"

result_markers:
  - ".searchList"
  - "#content"
  - ".result-list"
  - ".board-list"

